Traceback (most recent call last):
  File "gen_errors.py", line 1, in <module>
    if x == 0:
NameError: name 'x' is not defined

Traceback (most recent call last):
  File "gen_errors.py", line 1, in <module>
    'a' + 1
TypeError: cannot concatenate 'str' and 'int' objects

Traceback (most recent call last):
  File "gen_errors.py", line 1, in <module>
    fghb
NameError: name 'fghb' is not defined

Traceback (most recent call last):
  File "gen_errors.py", line 1
    if x == 0
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "probe", line 99, in <module>
    main()
  File "probe", line 96, in main
    run()
  File "probe", line SCOPE93, in run
    cli.cmdloop()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 215, in onecmd
    return self.default(line)
  File "/Users/alexbraun/google_drive/code/projects/sparse/python/sparse/views/probe_cli.py", line 69, in default
    self._api.spql_search(arg, display_fields=self._display_fields)
  File "/Users/alexbraun/google_drive/code/projects/sparse/python/sparse/frameworks/probe/probe_api.py", line 130, in spql_search
    results.read_json(self.data)
  File "/Users/alexbraun/google_drive/code/projects/sparse/python/sparse/frameworks/probe/probe_api.py", line 72, in data
    return self.database['data']
  File "/Users/alexbraun/google_drive/code/projects/sparse/python/sparse/frameworks/probe/probe_api.py", line 67, in database
    self.update()
  File "/Users/alexbraun/google_drive/code/projects/sparse/python/sparse/frameworks/probe/probe_api.py", line 87, in update
    self._database = self._backingstore.get_database()
  File "/Users/alexbraun/google_drive/code/projects/sparse/python/sparse/frameworks/probe/backingstore.py", line 69, in get_database
    self.update()
  File "/Users/alexbraun/google_drive/code/projects/sparse/python/sparse/frameworks/probe/qube_backingstore.py", line 256, in update
    self._job_update()
  File "/Users/alexbraun/google_drive/code/projects/sparse/python/sparse/frameworks/probe/qube_backingstore.py", line 158, in _job_update
    data['jobtype'] = data['name'].apply(lambda x: get_jobtype(x))
  File "/Library/Python/2.7/site-packages/pandas/core/series.py", line 1998, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "inference.pyx", line 1016, in pandas.lib.map_infer (pandas/lib.c:51482)
  File "/Users/alexbraun/google_drive/code/projects/sparse/python/sparse/frameworks/probe/qube_backingstore.py", line 158, in <lambda>
    data['jobtype'] = data['name'].apply(lambda x: get_jobtype(x))
  File "/Users/alexbraun/google_drive/code/projects/sparse/python/sparse/utilities/qube_utils.py", line 142, in get_jobtype
    flags=RE.IGNORECASE)
NameError: global name 'RE' is not defined